export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';

export const INIT_INGREDIENTS = 'INIT_INGREDIENTS';
export const LOADING_INGREDIENTS = 'LOADING_INGREDIENTS';
export const LOADING_INGREDIENTS_ERROR = 'LOADING_INGREDIENTS_ERROR';

export const HANDLE_ORDER_INIT ='HANDLE_ORDER_INIT';
export const HANDLE_ORDER_PURCHASE_SUCCESS = 'HANDLE_ORDER_PURCHASE_SUCCESS';
export const HANDLE_ORDER_PURCHASE_FAIL = 'HANDLE_ORDER_PURCHASE_FAIL';
export const HANDLE_ORDER_PURCHASE_START = 'HANDLE_ORDER_PURCHASE_START'
export const HANDLE_ORDER_SUBMIT = 'HANDLE_ORDER_SUBMIT';

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START'
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS'
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL'
